# Generated by Django 3.0 on 2023-02-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ImageLink',
            field=models.TextField(default='https://image.shutterstock.com/image-photo/gardening-senior-man-working-garden-260nw-1028568655.jpg'),
            preserve_default=False,
        ),
    ]
